image: alpine/latest

packages:
  - fluidsynth-dev
  - glew-dev
  - glfw-dev
  - libxml2-dev
  - libxrandr-dev

sources:
  - https://git.sr.ht/~gullik/gscore

tasks:
  - build: |
      cd gscore
      make
