# Build manifest for sourcehut (https://builds.sr.ht/~gullik/gscore)
image: alpine/latest

packages:
  - black
  - cppcheck
  - fluidsynth-dev
  - glew-dev
  - glfw-dev
  - libxml2-dev
  - libxrandr-dev

sources:
  - https://git.sr.ht/~gullik/gscore

tasks:
  - build: |
      cd gscore
      make
  - cppcheck: |
      cd gscore
      make cppcheck
  - black: |
      cd gscore
      make black
