const char* const FILE_FORMAT_SCHEMA =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n"
"  <xs:element name=\"gscore\">\n"
"    <xs:complexType>\n"
"      <xs:sequence>\n"
"        <xs:element name=\"score\">\n"
"          <xs:complexType>\n"
"            <xs:sequence>\n"
"              <xs:element name=\"metadata\" minOccurs=\"0\" maxOccurs=\"1\">\n"
"                <xs:complexType>\n"
"                  <xs:sequence>\n"
"                    <xs:any processContents=\"skip\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
"                  </xs:sequence>\n"
"                </xs:complexType>\n"
"              </xs:element>\n"
"              <xs:element name=\"blockdefs\">\n"
"                <xs:complexType>\n"
"                  <xs:sequence>\n"
"                    <xs:element name=\"blockdef\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
"                      <xs:complexType>\n"
"                        <xs:sequence>\n"
"                          <xs:element name=\"message\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
"                            <xs:complexType>\n"
"                              <xs:attribute name=\"time\" type=\"xs:decimal\" use=\"required\"/>\n"
"                              <xs:attribute name=\"type\" type=\"xs:nonNegativeInteger\" use=\"required\"/>\n"
"                              <xs:attribute name=\"pitch\" type=\"xs:nonNegativeInteger\" use=\"required\"/>\n"
"                              <xs:attribute name=\"velocity\" type=\"xs:decimal\" use=\"required\"/>\n"
"                            </xs:complexType>\n"
"                          </xs:element>\n"
"                        </xs:sequence>\n"
"                        <xs:attribute name=\"name\" type=\"xs:string\" use=\"required\"/>\n"
"                        <xs:attribute name=\"color\" type=\"xs:string\" use=\"required\"/>\n"
"                      </xs:complexType>\n"
"                    </xs:element>\n"
"                  </xs:sequence>\n"
"                </xs:complexType>\n"
"              </xs:element>\n"
"              <xs:element name=\"tracks\">\n"
"                <xs:complexType>\n"
"                  <xs:sequence>\n"
"                    <xs:element name=\"track\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
"                      <xs:complexType>\n"
"                        <xs:sequence>\n"
"                          <xs:element name=\"block\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
"                            <xs:complexType>\n"
"                              <xs:attribute name=\"name\" type=\"xs:string\"/>\n"
"                              <xs:attribute name=\"velocity\" type=\"xs:decimal\"/>\n"
"                            </xs:complexType>\n"
"                          </xs:element>\n"
"                        </xs:sequence>\n"
"                        <xs:attribute name=\"program\" type=\"xs:string\" use=\"required\"/>\n"
"                        <xs:attribute name=\"velocity\" type=\"xs:decimal\" use=\"required\"/>\n"
"                        <xs:attribute name=\"ignorenoteoff\" type=\"xs:nonNegativeInteger\" use=\"required\"/>\n"
"                      </xs:complexType>\n"
"                    </xs:element>\n"
"                  </xs:sequence>\n"
"                </xs:complexType>\n"
"              </xs:element>\n"
"            </xs:sequence>\n"
"            <xs:attribute name=\"tempo\" type=\"xs:positiveInteger\" use=\"required\"/>\n"
"            <xs:attribute name=\"keysignature\" type=\"xs:string\" use=\"required\"/>\n"
"            <xs:attribute name=\"beatspermeasure\" type=\"xs:positiveInteger\" use=\"required\"/>\n"
"          </xs:complexType>\n"
"        </xs:element>\n"
"      </xs:sequence>\n"
"      <xs:attribute name=\"version\" type=\"xs:string\" use=\"required\"/>\n"
"    </xs:complexType>\n"
"  </xs:element>\n"
"</xs:schema>\n";

